/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package muit.fs.junio22;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import muit.fs.junio2022.App;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
